# the base hostname & protocol for your site, e.g. http://example.com
url: ""

# the subpath of your site, e.g. /blog
baseurl: ""

# use /posts/post-name/ as permalink
permalink: /:title/

# the name of your site, e.g. ACME Corp.
title: "yaodong.dev"

plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/archives/:year/'
    tag: '/tags/:name/'
    category: '/categories/:name/'

exclude:
  - bin
  - node_modules
  - bun.lockb
  - Procfile.dev
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - tsconfig.json
  - README.md
  - .idea
  - .github
  - .devcontainer
  - .bun-version
